# Generated by Django 5.1.3 on 2024-11-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='listings/images/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='listings/images/', verbose_name='Изображение 2'),
        ),
    ]
